# Generated by Django 5.1.1 on 2024-09-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
