# Generated by Django 5.1.1 on 2024-09-12 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todoitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 18, 47, 38, 30371, tzinfo=datetime.timezone.utc), verbose_name='date-of-creation'),
        ),
    ]
