# Generated by Django 5.1.1 on 2024-09-12 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todolist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 19, 13, 38, 475715, tzinfo=datetime.timezone.utc), verbose_name='date-of-creation'),
        ),
    ]
