# Generated by Django 5.1.1 on 2024-09-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todolist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='date',
        ),
    ]
