# Generated by Django 5.1.1 on 2024-09-13 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_remove_todolist_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='List',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=256)),
                ('deadline_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.list')),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoItem',
        ),
    ]
