# Generated by Django 5.1.1 on 2024-09-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_rename_todolist_list_item_delete_todoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline_date',
            field=models.DateField(),
        ),
    ]
